<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [
    // Панель навигации:
    'NAV_HOME'       => 'Главная',
    'NAV_PAGES'      => 'Страницы',
    'NAV_BLOG'       => 'Блог',
    'NAV_PORTFOLIO'  => 'Портфолио',
    'NAV_SHORTCODES' => 'Шорткоды',
    'NAV_LOGIN'      => 'Вход',
    'NAV_LOGOUT'     => 'Выход',
    'NAV_PROFILE'    => 'Профиль',
    'NAV_ADMIN'      => 'Администрирование',

    'NAV_ABOUT' => '',
    'NAV_ABOUT2' => '',
    'NAV_SERVICES' => '',
    'NAV_PRICING' => '',
    'NAV_CONTACT_US' => '',
    'NAV_CONTACT_US_2' => '',
    'NAV_404_ERROR' => '',
    'NAV_COMING_SOON' => '',

    'NAV_BLOG_DEFAULT' => '',
    'NAV_TIMELINE_BLOG' => '',
    'NAV_2_COLUMNS_RIGHT_SIDEBAR' => '',
    'NAV_1_COLUMN_LEFT_SIDEBAR' => '',
    'NAV_BLOG_MASONARY' => '',
    'NAV_BLOG_DETAILS' => '',

    'NAV_PORTFOLIO_DEFAULT' => '',
    'NAV_ISOTOPE_3_COLUMNS_RIGHT_SIDEBAR' => '',
    'NAV_3_COLUMNS_RIGHT_SIDEBAR' => '',
    'NAV_3_COLUMNS_LEFT_SIDEBAR' => '',
    'NAV_2_COLUMNS' => '',
    'NAV_PORTFOLIO_DETAILS' => '',

];
